- name: config | apt proxy configuration
  template:
    src: "{{ apt_template }}"
    dest: /etc/apt/apt.conf.d/01proxy
  when: connect_to_proxy|bool
  tags:
    - apt-proxy

- name: config | http proxy configuration
  template:
    src: "{{ http_template }}"
    dest: /etc/profile.d/proxy.sh
  when: connect_to_proxy|bool
  tags:
    - http-proxy

- name: config | set timezone
  timezone:
    name: Europe/Paris
  tags:
    - time
