- name: install | apt upgrade
  apt:
    update_cache: yes
    upgrade: dist
  tags:
    - upgrade

- name: install | install utils
  apt:
    pkg: "{{ to_install }}"
  tags:
    - install

- name: install | unattended-upgrades activation
  shell: |
    echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
    dpkg-reconfigure -f noninteractive unattended-upgrades
    echo 'Unattended-Upgrade::Mail "root";' >> /etc/apt/apt.conf.d/50unattended-upgrades
  tags:
    - auto-upgrade
